version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - armin-joellenbeck
    labels: []
    schedule:
      interval: daily
  - package-ecosystem: bundler
    directories:
      - /playground-rb
      - /www
    allow:
      - dependency-type: all
    assignees:
      - armin-joellenbeck  
    labels: []
    schedule:
      interval: daily
  - package-ecosystem: docker
    directories:
      - /playground-rb
      - /www
    assignees:
      - armin-joellenbeck
    labels: []
    schedule:
      interval: daily
