version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    assignees:
      - armin-joellenbeck
    schedule:
      interval: daily
  - directory: /playground-ruby
    package-ecosystem: docker
    assignees:
      - armin-joellenbeck
    schedule:
      interval: daily
  - directory: /playground-ruby
    package-ecosystem: bundler
    allow:
      - dependency-type: all
    assignees:
      - armin-joellenbeck  
    schedule:
      interval: daily
  - directory: /www
    package-ecosystem: docker
    assignees:
      - armin-joellenbeck
    schedule:
      interval: daily
  - directory: /www
    package-ecosystem: bundler
    allow:
      - dependency-type: all
    assignees:
      - armin-joellenbeck
    schedule:
      interval: daily
