version: '3.8'

services:
  server:
    build:
      target: server
    deploy:
      replicas: 1
    ports:
      - published: 4000
        target: 4000
        protocol: tcp
  shell:
    build:
      target: shell
    deploy:
      replicas: 0
    volumes:
      - source: .
        target: /mnt
        type: bind
        
