x-service: &service
  image: ghcr.io/joellenbeck-net/dev
  volumes:
    - source: .
      target: /mnt/app
      type: bind
services:
  shell:
    command: bash
    <<: *service
  web:
    command: bundle exec jekyll serve --host 0.0.0.0 --port 8080
    ports:
      - protocol: tcp
        published: 8080
        target: 8080
    <<: *service
