x-service: &service
services:
  app:
    command: bundle exec jekyll serve --host 0.0.0.0 --port 8080
    image: ghcr.io/joellenbeck-net/jekyll
    ports:
      - protocol: tcp
        published: 8080
        target: 8080
    restart: always
  jekyll:
    command: bash
    deploy:
      replicas: 0
    image: ghcr.io/joellenbeck-net/jekyll
    volumes:
      - source: jekyll
        target: /mnt/app
        type: bind
  ruby:
    command: bash
    deploy:
      replicas: 0
    image: ghcr.io/joellenbeck-net/ruby
    volumes:
      - source: ruby
        target: /mnt/app
        type: bind
