x-service: &service
services:
  app:
    command: bundle exec jekyll serve --host 0.0.0.0 --port 8080
    image: ghcr.io/joellenbeck-net/www
    ports:
      - protocol: tcp
        published: 8080
        target: 8080
    restart: always
