source 'https://rubygems.org'

gem 'jekyll', '4.3.3', require: false
gem 'mocktail', '2.0.0'
gem 'rake', '13.2.1' # TODO: needed for installing google-protobuf 3.25.1
gem 'rubocop', '1.65.1', require: false
gem 'zeitwerk', '2.6.17'
