source 'https://rubygems.org'

ruby '3.3.0'

gem 'bundler', '2.5.1'
gem 'jekyll', '4.3.3', require: false
gem 'rake', '13.1.0' # TODO: needed for installing google-protobuf 3.25.1
gem 'rubocop', '1.59.0', require: false
