name: Commit
on:  
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_FROZEN: false
      BUNDLE_PATH: .bundle
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1.154.0
        with:
          bundler: default
          bundler-cache: true
          ruby-version: .ruby-version
      - name: Run rake
        run: bundle exec rake
      - name: Create tar archive
        run: mkdir -p tmp && tar cvf tmp.tar tmp
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-build
          path: tmp.tar
