name: Commit
on:
  push:
    branches-ignore:
      - main
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and Test
      run: ./bin/test
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public
