name: Commit
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_PATH: .bundle
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1.153.0
        with:
          bundler: default
          bundler-cache: true
          ruby-version: .ruby-version
      - name: Run rake
        run: bundle exec rake
