name: Commit
on:
  push:
    branches-ignore:
      - main
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: docker buildx bake --load
    - name: Extract public dir from www
      run: docker container cp $(docker container create ghcr.io/joellenbeck-net/www:latest):/app/public public
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public
