name: Commit
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_FROZEN: false
      BUNDLE_PATH: .bundle
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Setup ruby
        uses: ruby/setup-ruby@52b8784594ec115fd17094752708121dc5dabb47 # v1.154.0
        with:
          bundler: default
          bundler-cache: true
          ruby-version: .ruby-version
      - name: Run rake
        run: bundle exec rake
